export type Mode = "hybrid" | "web" | "maps";
export type MapsDepth = "fast" | "deep";

export type ProductOpportunity = "zirel_strong" | "zirel_medium" | "website_only" | "both_strong" | "skip";
export type NextAction = "call_now_high_priority" | "call_now_low_priority" | "test_whatsapp" | "email_first" | "skip" | "manual_review";
export type Source = "maps_site" | "maps_no_site" | "web";
export type BookingVisibility = "above_fold" | "below_fold" | "hidden" | "subflow" | "none";
export type BusinessSize = "small" | "medium" | "large" | "enterprise";
export type SiteStructureType = "single_site" | "multi_site" | "hub_gateway";
export type FunnelComplexity = "simple" | "multi_step" | "fragmented";
export type BusinessRelevance = "core" | "non_core";
export type EvidenceLevel = "high" | "medium" | "low";

export interface Lead {
  source: Source;
  businessName: string;
  website: string;
  mobilePhone: string;
  landlinePhone: string;
  email: string;
  emailQuality: "high" | "medium" | "low" | "none";
  owner: string;
  cityMatchScore: number;
  fitScore: number;
  refreshOpportunityScore: number;
  salesAngle: string;
  contactPriority: string;
  outreachTemplate: string;
  reasonFlags: string;
  address: string;
  mapsUrl: string;
  productOpportunity: ProductOpportunity;
  zirelFitScore: number;
  websiteRefreshScore: number;
  newWebsiteScore: number;
  urgencyScore: number;
  contactabilityScore: number;
  businessQualityScore: number;
  finalPriorityScore: number;
  nextAction: NextAction;
  reasonSummary: string;
  openingLine: string;
  zirelProblemScore: number;
  detectedPain: string;
  missingChannels: string;
  hasWhatsapp: boolean;
  whatsappEvidence: string;
  hasBooking: boolean;
  bookingVisibility: BookingVisibility;
  bookingProvider: string;
  bookingEvidence: string;
  hasIndirectBooking: boolean;
  siteStructureType: SiteStructureType;
  funnelComplexity: FunnelComplexity;
  hasFlowBooking: boolean;
  requiresManualReview: boolean;
  businessRelevance: BusinessRelevance;
  businessSize: BusinessSize;
  buyerFitScore: number;
  salesEaseScore: number;
  hasChatbot: boolean;
  chatbotProvider: string;
  chatbotEvidence: string;
  hasContactForm: boolean;
  onlyPhone: boolean;
  onlyLandline: boolean;
  reviewsCount: number;
  rating: number;
  categoryFit: string;
  seasonalityFit: string;
  priority: "HOT" | "WARM" | "COLD" | "SKIP";
  callPriority: "SUPER_HOT" | "HOT" | "WARM" | "SKIP";
  moneyOpportunityScore: number;
  proofSignal: string;
  hookType: "lost_leads" | "busy_staff" | "no_after_hours" | "no_booking" | "friction_contact";
  urgencyReason: string;
  objectionAngle: string;
  trafficSignal: string;
  callScript: string;
  validEmails: string;
  invalidEmailReason: string;
  checkedUrls: string;
  evidenceLevel: EvidenceLevel;
  whyThisLeadIsSellable: string;
}

export interface AppConfig {
  mode: Mode;
  mapsDepth: MapsDepth;
  city: string;
  keyword: string;
  maxResults: number;
  withWhois: boolean;
  debug: boolean;
  aiEnrich: boolean;
  aiMax: number;
  aiModel: string;
  zirelOnly: boolean;
}
